POST http://localhost:3000/board/articles3
Content-Type: application/json

{
  "id": "gg",
  "title": "this is title",
  "content": "this is content",
  "password": 1234
}

###

GET http://localhost:3000/board/articles